openapi: 3.0.3
info:
  title: Mortgages API
  version: 1.0.0
  description: |-
    A REST API Service for denying or approving Mortgages
  contact:
    email: josocas@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://localhost:8080/api
tags:
  - name: MortgageRate
    description: The mortgage rate object contains the fields; maturityPeriod (integer), interestRate (Percentage) and lastUpdate (Timestamp)

  - name: MortgageProposal
    description: The Mortgage check (proposal) contains at least the fields; income (Amount), maturityPeriod (integer), loanValue (Amount), homeValue (Amount)

  - name: CheckResult
    description: The result of checking the mortgage proposal

paths:
  /interest-rates:
    get:
      tags:
        - MortgageRate
      summary: Returns the list of all mortgage rates
      description: Returns the list of all mortgage rates
      operationId: listMortgageRates
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MortgageRate'
  /mortgage-check:
    post:
      tags:
        - MortgageProposal
      summary: Returns whether the mortgage proposal is feasible
      description: The mortgage check return if the mortgage is feasible (boolean) and the monthly costs (Amount) of the mortgage.
      operationId: checkMortgage
      requestBody:
        description: Mortgage proposal that needs to be checked
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MortgageProposal'
      responses:
        '200':
          description: The check was successfully done
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/CheckResult'
        '400':
          description: The check was not possible due to some missing field. Check the reject reason from response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckResult'
components:
  schemas:
    MortgageRate:
      type: object
      required:
        - maturityPeriod
        - interestRate
        - lastUpdate
      properties:
        maturityPeriod:
          type: integer
          format: integer
          example: 360
        interestRate:
          type: float
          example: 5.5
        lastUpdate:
          type: string
          format: date-time
    MortgageProposal:
      type: object
      required:
        - income
        - maturityPeriod
        - loanValue
        - homeValue
        - interestRate
        - currency
      properties:
        income:
          type: integer
          format: integer
          example: 15000
        maturityPeriod:
          type: integer
          example: 36
        loanValue:
          type: integer
          example: 100000
        homeValue:
          type: integer
          example: 180000
        interestRate:
          type: float
          example: 5.5
        currency:
          type: string
          example: EUR
    CheckResult:
      type: object
      required:
        - feasible
        - monthlyCost
        - currency
        - rejectReason
      properties:
        feasible:
          type: boolean
          example: false
        monthlyCost:
          type: float
          example: 500.25
        currency:
          type: string
          example: EUR
        rejectReason:
          type: string
          example: Exceeds home value