openapi: 3.0.3
info:
  title: Mortgages API
  version: 1.0.0
  description: |-
    A REST API Service for denying or approving Mortgages
  contact:
    email: josocas@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://localhost:8080/api
tags:
  - name: MortgageRate
    description: The mortgage rate object contains the fields; maturityPeriod (integer), interestRate (Percentage) and lastUpdate (Timestamp)

  - name: MortgageProposal
    description: The Mortgage check (proposal) contains at least the fields; income (Amount), maturityPeriod (integer), loanValue (Amount), homeValue (Amount)
paths:
  /interest-rates:
    get:
      tags:
        - MortgageRate
      summary: Returns the list of all mortgage rates
      description: Returns the list of all mortgage rates
      operationId: listMortgageRates
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MortgageRate'
  /mortgage-check:
    post:
      tags:
        - MortgageProposal
      summary: Returns whether the mortgage proposal is feasible
      description: The mortgage check return if the mortgage is feasible (boolean) and the monthly costs (Amount) of the mortgage.
      operationId: checkMortgage
      requestBody:
        description: Mortgage proposal that needs to be checked
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MortgageProposal'
      responses:
        '200':
          description: The check was successfully done
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CheckResult'
components:
  schemas:

    MortgageRate:
      type: object
      properties:
        maturityPeriod:
          type: integer
          format: int64
          example: 10
        interestRate:
          type: integer
          format: int64
          example: 5
        lastUpdate:
          type: string
          format: date-time

    MortgageProposal:
      type: object
      properties:
        income:
          type: integer
          format: int64
          example: 100000
        maturityPeriod:
          type: integer
          example: 5
        loanValue:
          type: integer
          example: 5
        currency:
          type: string
          example: EUR

    CheckResult:
      type: object
      properties:
        feasible:
          type: boolean
          example: false
        monthlyCost:
          type: integer
          example: 500
        currency:
          type: string
          example: EUR